<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Version>1.0.0</Version>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <AbpProjectType>app</AbpProjectType>
    <CikeVersion>1.0.9</CikeVersion>
    <MicrosoftPackageVersion>10.0.12</MicrosoftPackageVersion>
  </PropertyGroup>
</Project>
